### ISSUE TITLE
There was an error parsing `Gemfile`: unknown regexp options - rbyg.

### ISSUE THREAD

**Issue by suriyaa** [bunto/buntobot#2]
> See Travis CI log: https://travis-ci.org/bunto/buntobot/builds/151168440!

``` travis
$ bundle install --jobs=3 --retry=3
[!] There was an error parsing `Gemfile`: unknown regexp options - rbyg. Bundler cannot continue.
 #  from /home/travis/build/bunto/buntobot/Gemfile:1
 #  -------------------------------------------
 >  source https://rubygems.org
 #  
 #  -------------------------------------------
The command "eval bundle install --jobs=3 --retry=3" failed 3 times.
The command "bundle install --jobs=3 --retry=3" failed and exited with 4 during .
Your build has been stopped.
```

**Comment by suriyaa** [comment]
> :white_check_mark: Fixed!

Wrong: _`source https://rubygems.org`_
Correct: **`source 'https://rubygems.org'`**

**Comment by rudegentleman** [comment]
![image](https://user-images.githubusercontent.com/20442873/35198828-9d50a312-ff05-11e7-9103-8c7e481cd63d.png)
I need your help with this. I keep getting the above error whenever I run '_bundle install_' when trying to install metasploit. This is how my Gemfile looks like
![image](https://user-images.githubusercontent.com/20442873/35198960-cc963fc2-ff07-11e7-81ba-75d90bb08799.png)

**Comment by suriyaa** [comment]
@rudegentleman This issue looks different. 🤔 That's not the same [Gemfile](https://github.com/bunto/buntobot/blob/master/Gemfile) of this project.
